name: onyx_app
description: ONYX Main Mobile & Web Social Application.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Shared Core & UI Packages
  onyx_core:
    path: '../../packages/onyx_core'
  onyx_ui:
    path: '../../packages/onyx_ui'
    
  # Features Modules
  auth:
    path: '../../features/auth'
  feed:
    path: '../../features/feed'
  chat:
    path: '../../features/chat'

dev_dependencies:
  flutter_test:
    sdk: flutter
    
