name: onyx_monorepo
packages:
  - apps/*
  - packages/*
  - features/*

scripts:
  analyze:
    run: melos exec -- "dart analyze ."
    description: Run analyze on all packages.

  format:
    run: melos exec -- "dart format ."
    description: Format code in all packages.

  clean:
    run: melos exec -- "flutter clean"
    description: Clean all Flutter packages.
    
