name: auth
description: Authentication feature for ONYX app (login, register, profile).
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  onyx_core:
    path: '../../packages/onyx_core'
  onyx_ui:
    path: '../../packages/onyx_ui'

dev_dependencies:
  flutter_test:
    sdk: flutter
    
