name: onyx_ui
description: UI package for ONYX app containing theme, widgets, and assets.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  onyx_core:
    path: ../onyx_core

dev_dependencies:
  flutter_test:
    sdk: flutter
    
