name: onyx_admin
description: ONYX Admin Dashboard for managing platform users, content, and system analytics.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Shared Core & UI Packages
  onyx_core:
    path: '../../packages/onyx_core'
  onyx_ui:
    path: '../../packages/onyx_ui'

dev_dependencies:
  flutter_test:
    sdk: flutter
    
